name: Validate YAML Azure Pipeline

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
  markdown-deadlink-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World!"